"""GraphQL SDL generator from OSI semantic models.

Converts OSI YAML (datasets, relationships, metrics, actions, rules) into
a complete GraphQL schema (SDL string) compatible with Apollo / Cosmo.

Mapping rules:
- OSI datasets        → GraphQL Object Types
- OSI relationships   → GraphQL field references (multi-hop navigation)
- OSI metrics         → GraphQL Query fields (aggregate queries)
- OSI actions         → GraphQL Mutation types
- OSI ai_context      → GraphQL field/type descriptions (NL2GraphQL enhancement)
- OSI rules           → Schema descriptions + constraint hints
"""

from typing import Any, Dict, List, Optional

from .osi_model import (
    Action,
    ActionParameter,
    AIContext,
    DataSet,
    FieldDefinition,
    Metric,
    OSIModel,
    Relationship,
    Rule,
)


class GraphQLGenerator:
    """Generates a complete GraphQL SDL from an OSI semantic model.

    Produces output compatible with Apollo GraphOS and WunderGraph Cosmo.
    All GraphQL types include rich descriptions from ai_context, enabling
    AI agents to understand business semantics via introspection.
    """

    def __init__(self, model: OSIModel):
        self._model = model
        self._ds_map = model.dataset_map()
        self._rel_map = model.relationship_map()
        self._type_defs: List[str] = []
        self._enum_defs: List[str] = []
        self._input_defs: List[str] = []
        self._subscription_defs: List[str] = []

    # ─── Public API ────────────────────────────────────────────────────────────

    def generate(self) -> str:
        """Generate the complete GraphQL schema SDL."""
        self._type_defs.clear()
        self._enum_defs.clear()
        self._input_defs.clear()
        self._subscription_defs.clear()

        self._emit_header()
        self._emit_queries()
        self._emit_mutations()
        self._emit_enums()
        self._emit_dataset_types()
        self._emit_subscription_types()
        self._emit_filter_inputs()
        self._emit_order_enums()

        parts = [
            self._header(),
        ]
        if self._enum_defs:
            parts.append("\n\n".join(self._enum_defs))
        if self._input_defs:
            parts.append("\n\n".join(self._input_defs))
        if self._type_defs:
            parts.append("\n\n".join(self._type_defs))
        if self._subscription_defs:
            parts.append("\n\n".join(self._subscription_defs))

        return "\n\n".join(parts)

    def generate_operation(
        self, operation_type: str, dataset: str, fields: Optional[List[str]] = None
    ) -> str:
        """Generate a named GraphQL operation for a dataset.

        Args:
            operation_type: "query" or "mutation"
            dataset: Name of the dataset to query
            fields: List of field names to include (None = all fields)

        Returns:
            A named GraphQL operation string ready for MCP tool registration.
        """
        ds = self._ds_map.get(dataset)
        if not ds:
            return f"# Unknown dataset: {dataset}"

        lines = [f"{operation_type} {{"]
        lines.append(f"  {dataset.lower()}s {{")

        if fields:
            for f in fields:
                lines.append(f"    {f}")
        else:
            for f in ds.fields:
                if not f.relation_target:
                    lines.append(f"    {f.name}")

        lines.append("  }")
        lines.append("}")
        return "\n".join(lines)

    # ─── Header ───────────────────────────────────────────────────────────────

    def _emit_header(self):
        pass

    def _header(self) -> str:
        return (
            f"# Generated by OD Agent Semantic Backend\n"
            f"# Domain: {self._model.domain}\n"
            f"# Version: {self._model.version}\n"
            f"# https://github.com/your-org/od-agent\n"
        )

    # ─── Enums ────────────────────────────────────────────────────────────────

    def _emit_enums(self):
        seen = set()
        for ds in self._model.datasets:
            for f in ds.fields:
                if f.enum_values:
                    enum_name = f.enum_name or f"{ds.name}{f.name.title()}" if not f.name.islower() else f"{ds.name}{f.name.title()}"
                    if enum_name in seen:
                        continue
                    seen.add(enum_name)
                    self._enum_defs.append(self._build_enum(enum_name, f.enum_values, f.description))

    def _build_enum(self, name: str, values: List[str], description: str = "") -> str:
        desc = f'  """{description}"""\n' if description else ""
        value_lines = "".join(f"  {v}\n" for v in values)
        return f"{desc}enum {name} {{\n{value_lines}}}"

    def _infer_status_enum(self, ds: DataSet) -> Optional[Dict[str, Any]]:
        status_field_names = {"status", "state", "订单状态", "供应商状态", "物料状态"}
        for f in ds.fields:
            if f.name.lower() in status_field_names and f.enum_values:
                return {
                    "name": f"{ds.name}Status",
                    "values": f.enum_values,
                    "description": f"{ds.name} 状态枚举：{', '.join(f.enum_values)}",
                }
        return None

    # ─── Dataset Types ────────────────────────────────────────────────────────

    def _emit_dataset_types(self):
        for ds in self._model.datasets:
            self._type_defs.append(self._build_dataset_type(ds))

    def _build_dataset_type(self, ds: DataSet) -> str:
        lines: List[str] = []

        if ds.description:
            lines.append(f'  """"{ds.description}"""')
        elif ds.ai_context:
            lines.append(f'  """{ds.ai_context.to_description()}"""')

        lines.append(f"type {ds.name} {{")

        for f in ds.fields:
            lines.append(self._build_field(f, ds))

        for rel in self._rel_map.get(ds.name, []):
            lines.append(self._build_relation_field(rel, ds))

        for rule in self._model.rules:
            if rule.dataset == ds.name and rule.description:
                lines.append(f'  """{rule.description}"""')

        lines.append("}")
        return "\n".join(lines)

    def _build_field(self, f: FieldDefinition, ds: DataSet) -> str:
        desc_parts = []
        if f.description:
            desc_parts.append(f.description)
        if f.ai_hint:
            desc_parts.append(f"[AI] {f.ai_hint}")
        if f.enum_values:
            desc_parts.append(f"枚举值: {', '.join(f.enum_values)}")

        desc = ""
        if desc_parts:
            joined = "\n".join(desc_parts)
            desc = f'  """{joined.replace('"', '\\"')}"""\n  '

        required = "!" if f.required else ""
        list_marker = "[]" if f.is_list else ""
        gql_type = f.enum_name or f.gql_type
        return f"{desc}  {f.name}: {gql_type}{required}{list_marker}"

    def _build_relation_field(self, rel: Relationship, from_ds: DataSet) -> str:
        target = rel.to_dataset
        desc = f'  """关系: {rel.description}"""\n  ' if rel.description else "  "
        if rel.ai_hint:
            desc = f'  """[AI] {rel.ai_hint}"""\n  '
        list_suffix = "[]" if rel.relation_type in ("ONE_TO_MANY", "MANY_TO_MANY") else ""
        return f"{desc}  {target.lower()}s: [{target}!]{list_suffix}"

    # ─── Query ────────────────────────────────────────────────────────────────

    def _emit_queries(self):
        self._type_defs.append(self._build_query_type())

    def _build_query_type(self) -> str:
        lines = ['  """Query root — all data retrieval operations."""']
        lines.append("type Query {")

        for ds in self._model.datasets:
            pk = ds.primary_key_field()
            pk_arg = f"(id: ID!)" if pk else "(id: ID!)"
            lines.append(f"  {ds.name.lower()}s: [{ds.name}!]!")
            lines.append(f"  {ds.name.lower()}{pk_arg}: {ds.name}")

        for m in self._model.metrics:
            lines.append(self._build_metric_field(m))

        lines.append("}")
        return "\n".join(lines)

    def _build_metric_field(self, m: Metric) -> str:
        desc = f'  """{m.description}"""' if m.description else ""
        args = self._build_metric_args(m)
        return f"{desc}  {m.name}: {m.unit or 'Float'}"

    def _build_metric_args(self, m: Metric) -> str:
        if not m.filter_fields:
            return ""
        filters = ", ".join(f"{f}: String" for f in m.filter_fields)
        return f"({filters})"

    # ─── Mutation ─────────────────────────────────────────────────────────────

    def _emit_mutations(self):
        if not self._model.actions:
            return
        self._type_defs.append(self._build_mutation_type())

    def _build_mutation_type(self) -> str:
        lines = ['  """Mutation root — all state-changing operations."""']
        lines.append("type Mutation {")

        for a in self._model.actions:
            self._input_defs.append(self._build_action_input(a))
            lines.append(self._build_action_field(a))

        lines.append("}")
        return "\n".join(lines)

    def _build_action_field(self, a: Action) -> str:
        input_name = f"{a.name}Input"
        payload_name = f"{a.name}Payload"
        desc = f'  """{a.description}"""' if a.description else ""
        params = f"(input: {input_name}!): {payload_name}!"
        return f"{desc}  {a.name}{params}"

    def _build_action_input(self, a: Action) -> str:
        parts = [f"input {a.name}Input {{"]
        for p in a.parameters:
            required = "!" if p.required else ""
            parts.append(f"  {p.name}: {p.gql_type}{required}")
        parts.append("}")

        parts.append(f"\ntype {a.name}Payload {{")
        parts.append(f"  success: Boolean!")
        parts.append(f"  message: String")
        parts.append(f"  data: {a.dataset}")
        parts.append("}")

        return "\n".join(parts)

    # ─── Subscription ─────────────────────────────────────────────────────────

    def _emit_subscription_types(self):
        for ds in self._model.datasets:
            lines = [
                f"type {ds.name}Subscription {{",
                f"  {ds.name.lower()}Created: {ds.name}!",
                f"  {ds.name.lower()}Updated: {ds.name}!",
                f"}}",
            ]
            self._subscription_defs.append("\n".join(lines))

    # ─── Filter Inputs ────────────────────────────────────────────────────────

    def _emit_filter_inputs(self):
        for ds in self._model.datasets:
            fields = []
            for f in ds.fields:
                if f.gql_type in ("String", "ID"):
                    fields.append(f"  {f.name}: String")
                elif f.gql_type in ("Int", "Float"):
                    fields.append(f"  {f.name}: {f.gql_type}")
                    fields.append(f"  {f.name}_gte: {f.gql_type}")
                    fields.append(f"  {f.name}_lte: {f.gql_type}")
            if fields:
                self._input_defs.append(
                    f"input {ds.name}Filter {{\n" + "\n".join(fields) + "\n}"
                )

    def _emit_order_enums(self):
        for ds in self._model.datasets:
            values = [f.name for f in ds.fields if f.gql_type in ("String", "Int", "Float", "ID")]
            if values:
                self._input_defs.append(
                    f"enum {ds.name}OrderBy {{\n"
                    + "\n".join(f"  {v}\n  {v}_DESC" for v in values)
                    + "}"
                )
